language: python
sudo: false
python: 3.5
addons:
  apt:
    packages:
      - libev-dev
      - libevent-dev

before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - if [ $TOX_ENV = "py26"* ]; then sudo apt-get install python2.6 python2.6-dev; fi
  - if [ $TOX_ENV = "py33"  ]; then sudo apt-get install python3.3 python3.3-dev; fi

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  # Taken from https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350497804
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

env:
  - TOX_ENV=py26
  - TOX_ENV=py26-no-gevent
  - TOX_ENV=py27
  - TOX_ENV=py27-no-gevent
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=docs
  - TOX_ENV=flake8

script:
    - tox -e $TOX_ENV
install:
    - pip install tox

notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
